project:
  type: website

website:
  title: "MeLive"
  image: "melive_logo.png"
  page-navigation: true
  open-graph: true
  navbar:
    background: white
    logo: melive_logo.png
    logo-alt: "Melive logo."
    title: false
    collapse-below: lg
    left:
      - text: "Project Proposal"
        href: project_proposal.qmd
      - text: "Insights"
        href: insights.qmd
  sidebar:
    style: "floating"
    border: true
    search: true
    collapse-level: 1
    contents:
      - section: "Market Overview"
        contents:
          - posts/ANALYSIS/Market_Overview.qmd
      - section: "Historical Performance"
        contents:
          - posts/ANALYSIS/Overview_Performance_H22023.qmd
          - posts/ANALYSIS/Creator_Performance_H22023.qmd
  page-footer: 
    left: "Copyright 2024, Vi Duong" 


format:
  html:
    toc: true
    theme:
      light: [Yeti, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
      
freeze: true
editor: visual

