---
title: "Overview Analysis"
author: "Vi Duong"
date: "2024-03-15"
format:
  html:
    embed-resources: false
    toc: true
    number-sections: true
    theme: Sandstone
    fontsize: 1.1em
    linestretch: 1.7
---

```{r}
#| echo: false
#| include: false

library(pacman)
p_load(dplyr
       , readxl
       , janitor
       , lubridate
       , stringr
       , DT
       , purrr
       , highcharter
       , tidyr
       , reactable
       , tibble
       , networkD3
       , RDataOps
       , sf
       , knitr
       , htmltools
       , leaflet
       , plotly
       , googlesheets4
       , kableExtra
       , formattable
       , cohorts
       , openxlsx)

source("source_functions.R")

# Color
pink <- "#D81159"
lightpink <- "#FF6893"
lightgreen <- "#60BAAF"
green <- "#00524A"


```

```{r, include=FALSE}
load("../../../../[02] Ads Optimization/DATA/gmv_nmv.Rdata")
load("../../../../[02] Ads Optimization/DATA/livestream_traffic.Rdata")
load("../../../../[02] Ads Optimization/DATA/paid_sales_order.Rdata")
load("../../../../[02] Ads Optimization/DATA/unpaid_sales_order.Rdata")

link <- "https://docs.google.com/spreadsheets/d/1uuw0D6UYpjpZMLAOPfkzJM-8MoP4yKujC0iaE1rQkRE/edit#gid=0"

tiktok_rev <- ReadExcelFiles("../../../../[02] Ads Optimization/DATA/[00] Raw Data/tiktok_last6months_gmv.xlsx")

```

```{r, include=FALSE}
gmv_nmv <- gmv_nmv %>%
  mutate(est_gmv = case_when(gmv <= nmv ~ nmv * (1+0.53)
                             , TRUE ~ gmv)) %>% 
  filter(est_gmv > 0) %>% 
  mutate(creator_type = ifelse(is.na(creator_type), "partner", creator_type)) %>% 
  mutate(category = case_when(category %in% c("Womenswear", "womenswear") ~ "Trang phục nữ & Đồ lót"
                              , category %in% c("Menswear") ~ "Trang phục nam & Đồ lót"
                              , category %in% c("Beauty & personalcare") ~ "Chăm sóc sắc đẹp & Chăm sóc cá nhân"
                              , category %in% c("Household Appliances", "Home Suppliers") ~ "Đồ gia dụng"
                              # , category %in% c("Home Suppliers") ~ "Sửa chữa nhà cửa"
                              , category %in% c("Fashion Accessories") ~ "Phụ kiện thời trang"
                              , category %in% c("Shoes", "shoes") ~ "Giày"
                              , category %in% c("Kitchenswear") ~ "Đồ dùng nhà bếp"
                              , category %in% c("Health") ~ "Sức khỏe"
                              , category %in% c("Luggage & Bags","luggage and bags") ~ "Hành lý & Túi xách"
                              , category %in% c("Mom&baby") ~ "Trẻ sơ sinh & thai sản"
                              , category %in% c("Accessories") ~ "Phụ kiện trang sức & Phái sinh"
                              , category %in% c("Phone & Electronic") ~ "Điện thoại & Đồ điện tử"
                              , category %in% c("f&B", "F&B") ~ "Đồ ăn & Đồ uống"
                              , category %in% c("Grocery") ~ "Đồ ăn & Đồ uống"
                              , TRUE ~ "Unknown"))

sales_order <- paid_sales_order %>%
  mutate(payment = "online") %>% 
  bind_rows(unpaid_sales_order %>% mutate(payment = "cod")) %>% 
  filter(gmv > 0) %>% 
  mutate(content_type = case_when(content_type == "Livestream" ~ "a. Livestream"
                                  , content_type == "Video" ~ "b. Video"
                                  , content_type == "Showcase" ~ "c. Showcase")) %>% 
  mutate(creator_type = ifelse(is.na(creator_type), "partner", creator_type)) %>% 
  mutate(category = case_when(category %in% c("Womenswear", "womenswear") ~ "Trang phục nữ & Đồ lót"
                              , category %in% c("Menswear") ~ "Trang phục nam & Đồ lót"
                              , category %in% c("Beauty & personalcare") ~ "Chăm sóc sắc đẹp & Chăm sóc cá nhân"
                              , category %in% c("Household Appliances", "Home Suppliers") ~ "Đồ gia dụng"
                              # , category %in% c("Home Suppliers") ~ "Sửa chữa nhà cửa"
                              , category %in% c("Fashion Accessories") ~ "Phụ kiện thời trang"
                              , category %in% c("Shoes", "shoes") ~ "Giày"
                              , category %in% c("Kitchenswear") ~ "Đồ dùng nhà bếp"
                              , category %in% c("Health") ~ "Sức khỏe"
                              , category %in% c("Luggage & Bags","luggage and bags") ~ "Hành lý & Túi xách"
                              , category %in% c("Mom&baby") ~ "Trẻ sơ sinh & thai sản"
                              , category %in% c("Accessories") ~ "Phụ kiện trang sức & Phái sinh"
                              , category %in% c("Phone & Electronic") ~ "Điện thoại & Đồ điện tử"
                              , category %in% c("f&B", "F&B") ~ "Đồ ăn & Đồ uống"
                              , category %in% c("Grocery") ~ "Đồ ăn & Đồ uống"
                              , TRUE ~ "Unknown"))


# missing_seller <- sales_order %>%
#   mutate(is_seller_avail = ifelse(is.na(seller), FALSE, TRUE)) %>%
#   group_by(is_seller_avail) %>%
#   summarise(gmv = sum(gmv)
#             , nmv = sum(nmv)) %>%
#   ungroup() %>%
#   mutate(percent_gmv = gmv/sum(gmv)
#          , percent_nmv = nmv/sum(nmv))


```

# Summary

\*\* Data Source: gmv_nmv

```{r}
#| echo: false
#| warning: false
summary_seller_creator <- gmv_nmv %>% 
  summarise(first_month = min(month)
            , last_month = max(month)
            , no_months = n_distinct(month)
            , total_gmv = sum(gmv)/10^6
            , total_est_gmv = sum(est_gmv)/10^6
            , total_nmv = sum(nmv)/10^6
            , no_sellers = n_distinct(seller)
            , no_creators = n_distinct(creator)) %>% 
  ungroup() %>% 
  mutate(nmv_over_gmv = total_nmv/total_gmv) %>% 
  mutate(nmv_over_gmv = percent(nmv_over_gmv, digits = 1))

knitr::kable(summary_seller_creator
             , digits = 0
             , caption = "Number of active sellers and creators"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple")

monthly_summary_seller_creator <- gmv_nmv %>%
  group_by(month) %>% 
  summarise(no_sellers = n_distinct(seller)
            , no_creators = n_distinct(creator)
            , gmv = sum(gmv)/10^6
            , est_gmv = sum(est_gmv)/10^6
            , nmv = sum(nmv)/10^6) %>% 
  ungroup() %>% 
  summarise(avg_monthly_seller = mean(no_sellers)
            , avg_monthly_creators = mean(no_creators)
            , avg_monthly_gmv = mean(gmv)
            , avg_monthly_est_gmv = mean(est_gmv)
            , avg_monthly_nmv = mean(nmv))

knitr::kable(monthly_summary_seller_creator
             , digits = 0
             , caption = "Average active sellers and creators per month"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple")

```

# By Category

```{r}
#| echo: false
#| warning: false

summary_category <- gmv_nmv %>% 
  group_by(category) %>% 
  summarise(melive = sum(nmv)/10^9) %>% 
  ungroup() %>% 
  arrange(desc(melive)) %>% 
  full_join(tiktok_rev) %>%
  rename(tiktok = revenue_bil_vnd) %>% 
  mutate_if(is.numeric, replace_na, 0) %>% 
  mutate(percent_ml = percent(melive/sum(melive), digits = 1)) %>% 
  mutate(percent_tiktok = percent(tiktok/sum(tiktok), digits = 1)) %>%
  adorn_totals() %>% 
  mutate(ml_share_in_tiktok = percent(melive/tiktok, digits = 2))

knitr::kable(summary_category
             , digits = 0
             , caption = "GMV By Category vs Tiktok Shop (bil VND)"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple")

CreatePieChart(data = summary_category %>% filter(category != "Total")
               , colX = category
               , colY = melive) %>% 
  hc_title(text = "Melive Revenue Contribution By Category")

CreatePieChart(data = summary_category %>% filter(category != "Total")
               , colX = category
               , colY = tiktok) %>% 
  hc_title(text = "Tiktok Revenue Contribution By Category")

```

# Monthly Summary

## Monthly Revenue

### Total

```{r}
#| echo: false
#| warning: false

monthly_sales <- gmv_nmv %>% 
  group_by(month) %>% 
  summarise(gmv = sum(gmv)/10^6
            , est_gmv = sum(est_gmv)/10^6
            , nmv = sum(nmv)/10^6) %>% 
  ungroup() %>%
  arrange(month) 

# Table 

table <- monthly_sales %>%
  mutate(month = format(month, "%Y-%m")) %>% 
  pivot_longer(cols = c("gmv", "est_gmv", "nmv")
               , names_to = "metric"
               , values_to = "value") %>% 
  pivot_wider(names_from = c("month")
              , values_from = "value")

growth_rate <- monthly_sales %>% 
  mutate(month = format(month, "%Y-%m")) %>% 
  CalculateCMGR(valueCol = gmv, n = length(unique(monthly_sales$month)) -1) %>%
  rename(gmv_cmgr = CMGR) %>% 
  CalculateCMGR(valueCol = est_gmv, n = length(unique(monthly_sales$month)) -1) %>%
  rename(est_gmv_cmgr = CMGR) %>% 
  CalculateCMGR(valueCol = nmv, n = length(unique(monthly_sales$month)) -1) %>%
  rename(nmv_cmgr = CMGR) %>% 
  summarise(gmv_cmgr = percent(gmv_cmgr, digits = 1)
            , est_gmv_cmgr = percent(est_gmv_cmgr, digits = 1)
            , nmv_cmgr = percent(nmv_cmgr, digits = 1)) %>% 
  filter(!is.na(gmv_cmgr))

knitr::kable(growth_rate
             , digits = 0
             , caption = "Compound Monthly Growth Rate"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")

knitr::kable(table
             , digits = 0
             , caption = "Sales Through Time"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")


# Plot the chart

chart_data <- monthly_sales %>%
  mutate(month = format(month, "%Y-%m")) %>% 
  pivot_longer(cols = c("gmv", "est_gmv" ,"nmv")
               , names_to = "metric"
               , values_to = "value")

CreateCategoryChart(data = chart_data
                , colY = value
                , colX = month
                , groupCol = metric
                , colYTitle = "mil VND"
                , showAverageValue = FALSE) %>% 
  hc_title(text = "Sales Trend Over Time") %>% 
  hc_caption(text = "<i>Data Source: gmv_nmv<i>")
```

### GMV, NMV in November

-   To be checked: Why was there this huge gap?

```{r}
#| echo: false
#| warning: false

november_detail <- gmv_nmv %>%
  filter(month == "2023-11-01") %>% 
  group_by(creator, seller) %>% 
  summarise(gmv = sum(gmv)/10^6
            , est_gmv = sum(est_gmv)/10^6
            , nmv = sum(nmv)/10^6) %>% 
  ungroup() %>%
  arrange(desc(nmv)) %>% 
  head(10)

knitr::kable(november_detail
             , digits = 0
             , caption = "Sales Through Time"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")

```

## Monthly Seller

```{r}
#| echo: false
#| warning: false

monthly_seller <- gmv_nmv %>% 
  group_by(month) %>% 
  summarise(no_sellers = n_distinct(seller)) %>% 
  ungroup() %>%
  arrange(month)

# Table 
table <- monthly_seller %>%
  mutate(month = format(month, "%Y-%m")) %>% 
  pivot_wider(names_from = month
              , values_from = no_sellers)

growth_rate <- monthly_seller %>% 
  mutate(month = format(month, "%Y-%m")) %>% 
  CalculateCMGR(valueCol = no_sellers, n = length(unique(monthly_seller$month)) -1) %>% 
  summarise(CMGR = percent(CMGR, digits = 1)) %>% 
  filter(!is.na(CMGR))

knitr::kable(growth_rate
             , digits = 0
             , caption = "Compound Monthly Growth Rate"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")

knitr::kable(table
             , digits = 0
             , caption = "Number Of Sellers Through Time"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")

# Plot the chart

CreateLineChart(data = monthly_seller
                , colY = no_sellers
                , colX = month
                , colYTitle = "Number Of Sellers"
                , showAverageValue = TRUE) %>%
  hc_colors(CreateMetubColor()) %>% 
  hc_title(text = "Active Sellers Trend Over Time") %>% 
  hc_caption(text = "<i>Data Source: gmv_nmv<i>")
```

## Monthly Creator

```{r}
#| echo: false
#| warning: false

monthly_creator <- gmv_nmv %>% 
  group_by(month) %>% 
  summarise(no_creators = n_distinct(creator)) %>% 
  ungroup() %>%
  arrange(month)

# Table
table <- monthly_creator %>%
  mutate(month = format(month, "%Y-%m")) %>% 
  pivot_wider(names_from = month
              , values_from = no_creators)

growth_rate <- monthly_creator %>% 
  mutate(month = format(month, "%Y-%m")) %>% 
  CalculateCMGR(valueCol = no_creators, n = length(unique(monthly_creator$month)) -1) %>% 
  summarise(CMGR = percent(CMGR, digits = 1)) %>% 
  filter(!is.na(CMGR))

knitr::kable(growth_rate
             , digits = 0
             , caption = "Compound Monthly Growth Rate"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")

knitr::kable(table
             , digits = 0
             , caption = "Number Of Creators Through Time"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")

# Plot the chart

CreateLineChart(data = monthly_creator
                , colY = no_creators
                , colX = month
                , colYTitle = "Number Of Creators"
                , showAverageValue = TRUE) %>%
  hc_colors(CreateMetubColor()) %>% 
  hc_title(text = "Active Sellers Trend Over Time") %>% 
  hc_caption(text = "<i>Data Source: gmv_nmv<i>")

```

# Sales Order Overview

\*\* Data Source: Paid And Unpaid Orders

## Compare With GMV_NMV Source

```{r}
#| echo: false
#| warning: false


sum_nmv_gmv <- summary_seller_creator %>% 
  select(-total_est_gmv) %>% 
  mutate(source = "gmv_nmv") %>% 
  mutate(first_month = format(first_month,"%m-%Y")) %>%
  mutate(last_month = format(last_month,"%m-%Y"))

sum_so <- sales_order %>% 
  summarise(first_month = min(month)
            , last_month = max(month)
            , no_months = n_distinct(month)
            , total_gmv = sum(gmv)/10^6
            , total_nmv = sum(nmv)/10^6
            , no_sellers = n_distinct(seller)
            , no_creators = n_distinct(creator)) %>% 
  ungroup() %>% 
  mutate(nmv_over_gmv = total_nmv/total_gmv) %>% 
  mutate(nmv_over_gmv = percent(nmv_over_gmv, digits = 1))

knitr::kable(sum_so
             , digits = 0
             , caption = "Summary Paid And Unpaid Sales Order"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")


sum_so <- sum_so %>% 
  mutate(source = "paid_unpaid_sales_order")

compare <- sum_nmv_gmv %>% 
  bind_rows(sum_so) %>% 
  select(source, everything()) %>% 
  mutate(gap_gmv = percent((total_gmv - lag(total_gmv))/lag(total_gmv), digits = 1)) %>% 
  mutate(gap_nmv = percent((total_nmv - lag(total_nmv))/lag(total_nmv), digits = 1)) %>% 
  mutate(gap_sellers = percent((no_sellers - lag(no_sellers))/lag(no_sellers), digits = 1)) %>% 
  mutate(gap_creators = percent((no_creators - lag(no_creators))/lag(no_creators), digits = 1))


knitr::kable(compare
             , digits = 0
             , caption = "Compare GMV/NMV Gap 2 Sources"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")


```

## Total

```{r}
#| echo: false
#| warning: false

# check <- sales_order %>% 
#   mutate(gap = promotion_price/selling_price) %>% 
#   mutate(product_value = promotion_price * qty_sold) %>% 
#   mutate(gap = product_value - gmv)

sum_so <- sales_order %>% 
  summarise(total_gmv = sum(gmv)/10^6
            , total_nmv = sum(nmv)/10^6
            , qty_sold = sum(qty_sold)
            , no_gmv_orders = n_distinct(order_code)
            , no_nmv_orders = n_distinct(order_code[nmv > 0])
            , commission = sum(commission)/10^6
            , melive_commission = sum(melive_commission)/10^6
            , creator_commission = sum(creator_commission)/10^6
            , no_livestreams = n_distinct(content_id)
            , no_products = n_distinct(product_id)) %>% 
  ungroup()

knitr::kable(sum_so
             , digits = 0
             , caption = "Sales Order Summary P1"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")

sum_so <- sales_order %>% 
  summarise(total_gmv = sum(gmv)/10^6
            , total_nmv = sum(nmv)/10^6
            , qty_sold = sum(qty_sold)
            , no_gmv_orders = n_distinct(order_code)
            , no_nmv_orders = n_distinct(order_code[nmv > 0])
            , commission = sum(commission)/10^6
            , melive_commission = sum(melive_commission)/10^6
            , creator_commission = sum(creator_commission)/10^6
            , no_livestreams = n_distinct(content_id)
            , no_products = n_distinct(product_id)) %>% 
  ungroup() %>% 
  summarise(aov_gmv = total_gmv/no_gmv_orders * 10^6
         , aov_nmv = total_nmv/no_nmv_orders * 10^6
         , asp = total_gmv* 10^6/qty_sold
         , commission_rate = percent(commission/total_nmv, digits = 1)
         , melive_takerate = percent(melive_commission/commission, digits = 1)
         , ml_com_over_gmv = percent(melive_commission/total_gmv, digits = 1)
         , commission_per_livestream = commission/no_livestreams
         , gmv_per_livestream = total_gmv/no_livestreams)

knitr::kable(sum_so
             , digits = 0
             , caption = "Sales Order Summary P2"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")


```

## Monthly

```{r}
#| echo: false
#| warning: false

sum_so <- sales_order %>%
  group_by(month) %>% 
  summarise(total_gmv = sum(gmv)/10^6
            , total_nmv = sum(nmv)/10^6
            , qty_sold = sum(qty_sold)
            , no_gmv_orders = n_distinct(order_code)
            , no_nmv_orders = n_distinct(order_code[nmv > 0])
            , commission = sum(commission)/10^6
            , melive_commission = sum(melive_commission)/10^6
            , creator_commission = sum(creator_commission)/10^6
            , no_livestreams = n_distinct(content_id)
            , no_products = n_distinct(product_id)) %>% 
  ungroup()

knitr::kable(sum_so
             , digits = 0
             , caption = "Sales Order Summary P1"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")

sum_so <- sales_order %>%
  group_by(month) %>%
  summarise(total_gmv = sum(gmv)/10^6
            , total_nmv = sum(nmv)/10^6
            , qty_sold = sum(qty_sold)
            , no_gmv_orders = n_distinct(order_code)
            , no_nmv_orders = n_distinct(order_code[nmv > 0])
            , commission = sum(commission)/10^6
            , melive_commission = sum(melive_commission)/10^6
            , creator_commission = sum(creator_commission)/10^6
            , no_livestreams = n_distinct(content_id)
            , no_products = n_distinct(product_id)) %>% 
  ungroup() %>% 
  group_by(month) %>% 
  summarise(aov_gmv = total_gmv/no_gmv_orders * 10^6
         , aov_nmv = total_nmv/no_nmv_orders * 10^6
         , asp = total_gmv* 10^6/qty_sold
         , commission_rate = percent(commission/total_nmv, digits = 1)
         , melive_takerate = percent(melive_commission/commission, digits = 1)
         , ml_com_over_gmv = percent(melive_commission/total_gmv, digits = 1)
         , commission_per_livestream = commission/no_livestreams
         , gmv_per_livestream = total_gmv/no_livestreams)

knitr::kable(sum_so
             , digits = 0
             , caption = "Sales Order Summary P2"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")


```

## Content Type

```{r}
#| echo: false
#| warning: false

sum_so_content_type <- sales_order %>%
  group_by(content_type) %>% 
  summarise(total_gmv = sum(gmv)/10^6
            , total_nmv = sum(nmv)/10^6
            , qty_sold = sum(qty_sold)
            , no_gmv_orders = n_distinct(order_code)
            , no_nmv_orders = n_distinct(order_code[nmv > 0])
            , commission = sum(commission)/10^6
            , melive_commission = sum(melive_commission)/10^6
            , creator_commission = sum(creator_commission)/10^6
            , no_livestreams = n_distinct(content_id)
            , no_products = n_distinct(product_id)) %>% 
  ungroup() %>% 
  mutate(gmv_contribution = percent(total_gmv/sum(total_gmv), digits = 1)) %>% 
  select(content_type, total_gmv, gmv_contribution, everything())

knitr::kable(sum_so_content_type
             , digits = 0
             , caption = "Sales Order By Content Type P1"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")

sum_so_content_type <- sales_order %>%
  group_by(content_type) %>% 
  summarise(total_gmv = sum(gmv)/10^6
            , total_nmv = sum(nmv)/10^6
            , qty_sold = sum(qty_sold)
            , no_gmv_orders = n_distinct(order_code)
            , no_nmv_orders = n_distinct(order_code[nmv > 0])
            , commission = sum(commission)/10^6
            , melive_commission = sum(melive_commission)/10^6
            , creator_commission = sum(creator_commission)/10^6
            , no_livestreams = n_distinct(content_id)
            , no_products = n_distinct(product_id)) %>% 
  ungroup() %>%
  group_by(content_type) %>% 
  summarise(aov_gmv = total_gmv/no_gmv_orders * 10^6
            , aov_nmv = total_nmv/no_nmv_orders * 10^6
            , asp = total_gmv* 10^6/qty_sold
            , commission_rate = percent(commission/total_nmv, digits = 1)
            , melive_takerate = percent(melive_commission/commission, digits = 1)
            , ml_com_over_gmv = percent(melive_commission/total_gmv, digits = 1)
            , commission_per_livestream = commission/no_livestreams
            , gmv_per_livestream = total_gmv/no_livestreams) %>% 
  ungroup()

knitr::kable(sum_so_content_type
             , digits = 0
             , caption = "Sales Order By Content Type P2"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")


```

# Livestream Data Review

\*\* Data Source: Livestream Traffic

## Total

```{r}
#| echo: false
#| warning: false

sum_lv <- livestream_traffic %>%
   summarise(first_month = min(month)
            , last_month = max(month)
            , no_months = n_distinct(month)
            , total_gmv = sum(gmv)/10^3
            , no_livestreams = n_distinct(livestream_id)
            , no_creators = n_distinct(creator)
            , total_view = sum(total_view)
            , total_ads_gmv = sum(ads_gmv)/10^3
            , total_ads_spent = sum(ads_spent)/10^3) %>% 
  ungroup() %>% 
  mutate(ads_gmv_contrib = percent(total_ads_gmv/total_gmv, digits = 1)
         , roas = total_ads_gmv/total_ads_spent
         , gmv_per_livestream = total_gmv/no_livestreams)

knitr::kable(sum_lv
             , digits = 0
             , caption = "Livestream Summary"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")



```

## By Month

```{r}
#| echo: false
#| warning: false

sum_lv <- livestream_traffic %>%
  group_by(month) %>% 
   summarise(total_gmv = sum(gmv)/10^3
            , no_livestreams = n_distinct(livestream_id)
            , no_creators = n_distinct(creator)
            , total_view = sum(total_view)
            , total_ads_gmv = sum(ads_gmv)/10^3
            , total_ads_spent = sum(ads_spent)/10^3) %>% 
  ungroup() %>% 
  mutate(ads_gmv_contrib = percent(total_ads_gmv/total_gmv, digits = 1)
         , roas = total_ads_gmv/total_ads_spent
         , gmv_per_livestream = total_gmv/no_livestreams)

knitr::kable(sum_lv
             , digits = 0
             , caption = "Livestream Summary By Month"
             , format.args = list(big.mark = ",", scientific = FALSE)
             , "simple") %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped")



```
